imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        main:
            http_basic: ~
            logout_on_user_change: true

services:
    AppBundle\Service\UserManager:
        public: true
        autowire: true

    AppBundle\Service\RoomManager:
        public: true
        autowire: true
