app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_login_check:
    path: /login_check
    methods: POST

app_logout:
    path: /logout
    methods: GET

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.yaml'

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /message
