# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_email_user_provider:
            entity:
                class: AppBundle:User
                property: email

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_COMPANY:     ROLE_USER
        ROLE_WEBMASTER:   ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            user_checker: AppBundle\Security\BannedChecker
            remember_me:
                name: rememberme
                secret: '%secret%'
                lifetime: 2592000
                path: /
                always_remember_me: true
            form_login:
                login_path: app_login
                username_parameter: login[email]
                password_parameter: login[password]
                provider: database_email_user_provider
                default_target_path: app_index
                failure_handler: AppBundle\Security\AuthenticationFailureHandler
            guard:
                authenticators:
                    - AppBundle\Security\AccessTokenAuthenticator
            logout: ~

    access_control:
        - { path: ^/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registered, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/banned, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/confirm/links, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/telephony/callback, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/app/status, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/payment, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/stub, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/dashboard, roles: ROLE_WEBMASTER }
        - { path: ^/telephony/calls, roles: ROLE_COMPANY }
        - { path: ^/company/update, roles: ROLE_COMPANY }
        - { path: ^/office/update, roles: ROLE_COMPANY }
        - { path: ^/, roles: ROLE_USER}
