parameters:

  nb_smsru_api_id: '07eb00aa-e1d0-5664-09af-0a454feb3aa7'

  nb_esputik_login: 'info@cuba-web.ru'
  nb_esputik_password: 'Qwerty271205'
  nb_smsru_esputik_event_push_key: 'q4g245h245j53wj357j'

  nb_esputik_tempalte_email_registration: '2031908'
  nb_esputik_tempalte_email_api_change: '2032880'
  nb_esputik_tempalte_email_balance_charge: '2032909'
  nb_esputik_tempalte_email_balance_lower_1500: '2032951'
  nb_esputik_tempalte_email_balance_lower_40: '2032994'
  nb_esputik_tempalte_email_support_response: '2033036'
  nb_esputik_tempalte_email_new_lead_in_room: '2033067'
  nb_esputik_tempalte_email_no_visiting_for_14_days: '2033106'
  nb_esputik_tempalte_email_new_arbitraj: '2033137'
  nb_esputik_tempalte_email_new_support_contact: '2033457'
  nb_esputik_tempalte_email_balance_withdrawl_for_user: '2034441'
  nb_esputik_tempalte_email_request_balance_withdrawl: '2033480'
  nb_esputik_tempalte_email_balance_withdrawl_fail: '2034460'
  nb_esputik_tempalte_email_balance_withdrawl_success: '2034473'
  nb_esputik_tempalte_email_password_change_request: '2034484'
  nb_esputik_tempalte_email_password_change_success: '2034499'

  telegram_bot_id: ""
  telegram_bot_name: ""

services:

  _defaults:
    autowire: true

  NotificationBundle\:
    resource: '../../*'
    exclude: '../../{Entity,Repository,Event,Client,tests}'

  Zelenin\SmsRu\Auth\ApiIdAuth:
    arguments:
      - '%nb_smsru_api_id%'

  Zelenin\SmsRu\Api:
    arguments:
      - '@Zelenin\SmsRu\Auth\ApiIdAuth'

  Longman\TelegramBot\Telegram:
    arguments:
      - '%telegram_bot_id%'
      - '%telegram_bot_name%'

  Brownie\ESputnik\Config:
    arguments:
      - { login: '%nb_esputik_login%', password: '%nb_esputik_password%'}

  Brownie\ESputnik\HTTPClient\CurlClient:

  Brownie\ESputnik\ESputnik:

  Brownie\ESputnik\HTTPClient\HTTPClient:

  notification_bundle.web_push_client:
    class: NotificationBundle\Client\EsputnikWebPushClient
    arguments:
      $eventPushKey: '%nb_smsru_esputik_event_push_key%'

  notification_bundle.email_client:
    class: NotificationBundle\Client\EsputnikEmailClient

  notification_bundle.sms_client:
    class: NotificationBundle\Client\SmsRuClient

  notification_bundle.internal_client:
    class: NotificationBundle\Client\InternalClient

  notification_bundle.telegram_client:
    class: NotificationBundle\Client\TelegramClient

  Brownie\ESputnik\HTTPClient\Client: '@Brownie\ESputnik\HTTPClient\CurlClient'

  NotificationBundle\EventSubscriber\ConfigureTelegramEventSubscriber:
    autowire: true
    tags:
      - { name: kernel.event_subscriber }

