parameters:

  nb_smsru_api_id: '07eb00aa-e1d0-5664-09af-0a454feb3aa7'

  nb_esputik_login: 'info@cuba-web.ru'
  nb_esputik_password: 'Qwerty271205'
  nb_smsru_esputik_event_push_key: 'q4g245h245j53wj357j'

  telegram_bot_id: ""
  telegram_bot_name: ""

services:

  _defaults:
    autowire: true
    autoconfigure: true

  NotificationBundle\:
    resource: '../../*'
    exclude: '../../{Entity,Event,tests}'

  Zelenin\SmsRu\Auth\ApiIdAuth:
    arguments:
      - '%nb_smsru_api_id%'

  Zelenin\SmsRu\Api:
    arguments:
      - '@Zelenin\SmsRu\Auth\ApiIdAuth'

  Longman\TelegramBot\Telegram:
    arguments:
      - '%telegram_bot_id%'
      - '%telegram_bot_name%'

  Brownie\ESputnik\Config:
    arguments:
      - { login: '%nb_esputik_login%', password: '%nb_esputik_password%'}

  Brownie\ESputnik\HTTPClient\CurlClient:

  Brownie\ESputnik\ESputnik:

  Brownie\ESputnik\HTTPClient\HTTPClient:

  NotificationBundle\Client\EsputnikWebPushClient:
    arguments:
      $eventPushKey: '%nb_smsru_esputik_event_push_key%'

  Brownie\ESputnik\HTTPClient\Client: '@Brownie\ESputnik\HTTPClient\CurlClient'

  NotificationBundle\EventSubscriber\ConfigureTelegramEventSubscriber:
    autowire: true
    tags:
      - { name: kernel.event_subscriber }
